namespace FFPRSaveEditorGUI {
    public class Item {
        public int contentId { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string type { get; set; }
    }

    public class NormalItems {
        public static Item GetItem(int contentId, Type saveType) {
            Item item = null;

            if (saveType.FullName.Contains("FF1")) {
                item = FF1Items.SingleOrDefault(x => x.contentId == contentId);
            } else if (saveType.FullName.Contains("FF2")) {
                item = FF2Items.SingleOrDefault(x => x.contentId == contentId);
            } else if (saveType.FullName.Contains("FF3")) {
                item = FF3Items.SingleOrDefault(x => x.contentId == contentId);
            } else if (saveType.FullName.Contains("FF4")) {
                item = FF4Items.SingleOrDefault(x => x.contentId == contentId);
            } else if (saveType.FullName.Contains("FF5")) {
                item = FF5Items.SingleOrDefault(x => x.contentId == contentId);
            } else if (saveType.FullName.Contains("FF6")) {
                item = FF6Items.SingleOrDefault(x => x.contentId == contentId);
            }

            return item != null ? item : new Item() { contentId = contentId, name = $"Unknown Item #{contentId:d3}", description = "Unknown", type = "Unknown" };
        }

        public static List<Item> GetItems(Type saveType) {
            if (saveType.FullName.Contains("FF1")) {
                return FF1Items;
            } else if (saveType.FullName.Contains("FF2")) {
                return FF2Items;
            } else if (saveType.FullName.Contains("FF3")) {
                return FF3Items;
            } else if (saveType.FullName.Contains("FF4")) {
                return FF4Items;
            } else if (saveType.FullName.Contains("FF5")) {
                return FF5Items;
            } else if (saveType.FullName.Contains("FF6")) {
                return FF6Items;
            }

            return null;
        }

        public static List<Item> FF1Items = new List<Item>() {
            new Item() { contentId = 2, name = "Potion", type = "Item", description = "Restores 50 HP." },
            new Item() { contentId = 3, name = "Hi-Potion", type = "Item", description = "Restores 150 HP." },
            new Item() { contentId = 4, name = "X-Potion", type = "Item", description = "Fully restores HP." },
            new Item() { contentId = 5, name = "Ether", type = "Item", description = "Restores 1 MP for each magic level." },
            new Item() { contentId = 7, name = "Dry Ether", type = "Item", description = "Restores 5 MP for each magic level." },
            new Item() { contentId = 8, name = "Elixir", type = "Item", description = "Fully restores HP and MP." },
            new Item() { contentId = 10, name = "Phoenix Down", type = "Item", description = "Revives one KO'd ally." },
            new Item() { contentId = 11, name = "Antidote", type = "Item", description = "Cures poison." },
            new Item() { contentId = 12, name = "Eye Drops", type = "Item", description = "Cures darkness." },
            new Item() { contentId = 13, name = "Echo Grass", type = "Item", description = "Cures silence." },
            new Item() { contentId = 14, name = "Gold Needle", type = "Item", description = "Cures stone." },
            new Item() { contentId = 15, name = "Remedy", type = "Item", description = "Cures ailments except stone and KO." },
            new Item() { contentId = 17, name = "Sleeping Bag", type = "Item", description = "Partially restores the party's HP.\nCan only be used in the field." },
            new Item() { contentId = 18, name = "Tent", type = "Item", description = "Partially restores the party's HP and MP.\nCan only be used in the field." },
            new Item() { contentId = 19, name = "Cottage", type = "Item", description = "Fully restores the party's HP and MP.\nCan only be used in the field." },
            new Item() { contentId = 32, name = "Giant's Tonic", type = "Item", description = "Temporarily raises max HP." },
            new Item() { contentId = 34, name = "Strength Tonic", type = "Item", description = "Temporarily raises attack." },
            new Item() { contentId = 35, name = "Protect Drink", type = "Item", description = "Temporarily raises defense." },
            new Item() { contentId = 36, name = "Speed Drink", type = "Item", description = "Temporarily raises agility." },
            new Item() { contentId = 62, name = "Empty", type = "Weapon", description = "" },
            new Item() { contentId = 63, name = "Knife", type = "Weapon", description = "A small knife." },
            new Item() { contentId = 64, name = "Dagger", type = "Weapon", description = "A large knife." },
            new Item() { contentId = 65, name = "Mythril Knife", type = "Weapon", description = "A knife wrought from mythril." },
            new Item() { contentId = 67, name = "Cat Claws", type = "Weapon", description = "A weapon with razor-sharp blades." },
            new Item() { contentId = 71, name = "Rapier", type = "Weapon", description = "A sword with a slender blade." },
            new Item() { contentId = 72, name = "Saber", type = "Weapon", description = "A long sword made for piercing." },
            new Item() { contentId = 73, name = "Broadsword", type = "Weapon", description = "A sword with a wide, double-edged blade." },
            new Item() { contentId = 74, name = "Werebuster", type = "Weapon", description = "A sword that is effective against beasts." },
            new Item() { contentId = 75, name = "Rune Blade", type = "Weapon", description = "A sword that is effective against spellcasters." },
            new Item() { contentId = 76, name = "Wyrmkiller", type = "Weapon", description = "A sword that is effective against dragons." },
            new Item() { contentId = 77, name = "Coral Sword", type = "Weapon", description = "A sword that is effective against aquatic enemies." },
            new Item() { contentId = 78, name = "Longsword", type = "Weapon", description = "A large, double-edged sword." },
            new Item() { contentId = 79, name = "Great Sword", type = "Weapon", description = "A sword that is effective against giants." },
            new Item() { contentId = 80, name = "Razer", type = "Weapon", description = "A saber that casts Scourge when used." },
            new Item() { contentId = 81, name = "Mythril Sword", type = "Weapon", description = "A sword wrought from mythril." },
            new Item() { contentId = 82, name = "Vorpal Sword", type = "Weapon", description = "A very sharp crescent blade." },
            new Item() { contentId = 83, name = "Flame Sword", type = "Weapon", description = "A sword imbued with the power of fire." },
            new Item() { contentId = 86, name = "Ice Brand", type = "Weapon", description = "A sword imbued with the power of ice." },
            new Item() { contentId = 87, name = "Defender", type = "Weapon", description = "A sword that casts Blink when used." },
            new Item() { contentId = 89, name = "Sun Blade", type = "Weapon", description = "A sword that is effective against the undead." },
            new Item() { contentId = 92, name = "Excalibur", type = "Weapon", description = "A sword crafted from a legendary metal; effective against all types of enemies." },
            new Item() { contentId = 96, name = "Scimitar", type = "Weapon", description = "A sword with a curved blade." },
            new Item() { contentId = 97, name = "Falchion", type = "Weapon", description = "A sword that widens toward its tip." },
            new Item() { contentId = 100, name = "Sasuke's Blade", type = "Weapon", description = "A small katana used by ninja." },
            new Item() { contentId = 103, name = "Masamune", type = "Weapon", description = "A legendary katana without match." },
            new Item() { contentId = 104, name = "Nunchaku", type = "Weapon", description = "Wooden nunchaku." },
            new Item() { contentId = 105, name = "Iron Nunchaku", type = "Weapon", description = "Nunchaku made of iron." },
            new Item() { contentId = 106, name = "Battle Axe", type = "Weapon", description = "An axe made for battle." },
            new Item() { contentId = 107, name = "Great Axe", type = "Weapon", description = "A large axe made for battle." },
            new Item() { contentId = 109, name = "Mythril Axe", type = "Weapon", description = "An axe wrought from mythril." },
            new Item() { contentId = 110, name = "Light Axe", type = "Weapon", description = "An axe that is effective against the undead; casts Diara when used." },
            new Item() { contentId = 114, name = "Hammer", type = "Weapon", description = "A hammer made for battle." },
            new Item() { contentId = 115, name = "Mythril Hammer", type = "Weapon", description = "A hammer wrought from mythril." },
            new Item() { contentId = 116, name = "Thor's Hammer", type = "Weapon", description = "A hammer that casts Thundara when used." },
            new Item() { contentId = 118, name = "Staff", type = "Weapon", description = "A wooden staff." },
            new Item() { contentId = 119, name = "Healing Staff", type = "Weapon", description = "A staff that casts Heal when used." },
            new Item() { contentId = 120, name = "Power Staff", type = "Weapon", description = "A staff with good attack power." },
            new Item() { contentId = 121, name = "Mage's Staff", type = "Weapon", description = "A staff that casts Fira when used." },
            new Item() { contentId = 122, name = "Crosier", type = "Weapon", description = "A staff topped with an iron ring." },
            new Item() { contentId = 123, name = "Wizard's Staff", type = "Weapon", description = "A staff that casts Confuse when used." },
            new Item() { contentId = 130, name = "None", type = "Armor - Shield", description = "" },
            new Item() { contentId = 131, name = "None", type = "Armor - Body", description = "" },
            new Item() { contentId = 132, name = "None", type = "Armor - Head", description = "" },
            new Item() { contentId = 133, name = "None", type = "Armor - Arms", description = "" },
            new Item() { contentId = 134, name = "Clothes", type = "Armor - Body", description = "Ordinary clothing." },
            new Item() { contentId = 136, name = "White Robe", type = "Armor - Body", description = "A robe that guards against fire and instant death; casts Invisira when used." },
            new Item() { contentId = 137, name = "Black Robe", type = "Armor - Body", description = "A robe that guards against ice and time irregularities; casts Blizzara when used." },
            new Item() { contentId = 145, name = "Leather Armor", type = "Armor - Body", description = "Armor made of hardened leather." },
            new Item() { contentId = 146, name = "Chain Mail", type = "Armor - Body", description = "Mail of interwoven chain links." },
            new Item() { contentId = 147, name = "Mythril Mail", type = "Armor - Body", description = "Mail crafted from mythril." },
            new Item() { contentId = 148, name = "Iron Armor", type = "Armor - Body", description = "Armor made of thinly hammered iron." },
            new Item() { contentId = 149, name = "Ice Armor", type = "Armor - Body", description = "Armor infused with the power of ice that guards against fire." },
            new Item() { contentId = 150, name = "Flame Mail", type = "Armor - Body", description = "Mail infused with the power of fire that guards against ice." },
            new Item() { contentId = 151, name = "Knight's Armor", type = "Armor - Body", description = "Armor crafted from steel plate." },
            new Item() { contentId = 153, name = "Diamond Armor", type = "Armor - Body", description = "Armor crafted from diamond that guards against lightning." },
            new Item() { contentId = 154, name = "Dragon Mail", type = "Armor - Body", description = "Mail fashioned from dragon scales that guards against fire and ice." },
            new Item() { contentId = 156, name = "Copper Armlet", type = "Armor - Body", description = "An armlet crafted from copper." },
            new Item() { contentId = 157, name = "Silver Armlet", type = "Armor - Body", description = "An armlet of worked silver." },
            new Item() { contentId = 158, name = "Ruby Armlet", type = "Armor - Body", description = "An armlet ornamented with rubies." },
            new Item() { contentId = 160, name = "Diamond Armlet", type = "Armor - Body", description = "An armlet adorned with diamonds." },
            new Item() { contentId = 161, name = "Leather Shield", type = "Armor - Shield", description = "A shield made of hardened leather." },
            new Item() { contentId = 162, name = "Buckler", type = "Armor - Shield", description = "A small shield." },
            new Item() { contentId = 163, name = "Iron Shield", type = "Armor - Shield", description = "A shield wrought from iron." },
            new Item() { contentId = 164, name = "Mythril Shield", type = "Armor - Shield", description = "A shield crafted from mythril." },
            new Item() { contentId = 165, name = "Ice Shield", type = "Armor - Shield", description = "A shield imbued with the power of ice that guards against fire." },
            new Item() { contentId = 166, name = "Flame Shield", type = "Armor - Shield", description = "A shield imbued with the power of fire that guards against ice." },
            new Item() { contentId = 168, name = "Diamond Shield", type = "Armor - Shield", description = "A shield made of diamond that guards against lightning." },
            new Item() { contentId = 170, name = "Aegis Shield", type = "Armor - Shield", description = "A shield that guards against stone and poison." },
            new Item() { contentId = 173, name = "Protect Cloak", type = "Armor - Shield", description = "A large cloak worn over armor." },
            new Item() { contentId = 175, name = "Leather Cap", type = "Armor - Head", description = "A cap made of leather." },
            new Item() { contentId = 183, name = "Ribbon", type = "Armor - Head", description = "A ribbon that guards against elemental attacks and status effects." },
            new Item() { contentId = 184, name = "Helm", type = "Armor - Head", description = "A small helm." },
            new Item() { contentId = 185, name = "Great Helm", type = "Armor - Head", description = "A helm that covers the entire head." },
            new Item() { contentId = 186, name = "Healing Helm", type = "Armor - Head", description = "A helm that casts Heal when used." },
            new Item() { contentId = 187, name = "Mythril Helm", type = "Armor - Head", description = "A helm wrought from mythril." },
            new Item() { contentId = 188, name = "Diamond Helm", type = "Armor - Head", description = "A helm made of diamond." },
            new Item() { contentId = 191, name = "Leather Gloves", type = "Armor - Arms", description = "Gloves made of leather." },
            new Item() { contentId = 192, name = "Bronze Gloves", type = "Armor - Arms", description = "Gloves made of bronze." },
            new Item() { contentId = 193, name = "Steel Gloves", type = "Armor - Arms", description = "Gloves made of steel." },
            new Item() { contentId = 194, name = "Gauntlets", type = "Armor - Arms", description = "Gloves that cast Thundara when used." },
            new Item() { contentId = 195, name = "Giant's Gloves", type = "Armor - Arms", description = "Gloves that cast Saber when used." },
            new Item() { contentId = 197, name = "Mythril Gloves", type = "Armor - Arms", description = "Gloves made of mythril." },
            new Item() { contentId = 198, name = "Diamond Gloves", type = "Armor - Arms", description = "Gloves made of diamond." },
            new Item() { contentId = 202, name = "Protect Ring", type = "Armor - Arms", description = "A ring that guards against instant death." },

        };

        // TODOX No items for FF2 yet
        public static List<Item> FF2Items = new List<Item>() {
        };

        // TODOX No items for FF3 yet
        public static List<Item> FF3Items = new List<Item>() {
        };

        public static List<Item> FF4Items = new List<Item>() {
            new Item() { contentId = 2, name = "Potion", type = "Item", description = "Recovers HP." },
            new Item() { contentId = 3, name = "Hi-Potion", type = "Item", description = "Recovers HP." },
            new Item() { contentId = 4, name = "X-Potion", type = "Item", description = "Recovers HP." },
            new Item() { contentId = 5, name = "Ether", type = "Item", description = "Recovers MP." },
            new Item() { contentId = 6, name = "Dry Ether", type = "Item", description = "Recovers MP." },
            new Item() { contentId = 7, name = "Elixir", type = "Item", description = "Fully recovers HP and MP." },
            new Item() { contentId = 9, name = "Phoenix Down", type = "Item", description = "Revives an ally from the KO status." },
            new Item() { contentId = 10, name = "Gold Needle", type = "Item", description = "Cures an ally of petrification." },
            new Item() { contentId = 11, name = "Maiden's Kiss", type = "Item", description = "Cures an ally of the toad status." },
            new Item() { contentId = 12, name = "Mallet", type = "Item", description = "Cures an ally of mini." },
            new Item() { contentId = 13, name = "Diet Food", type = "Item", description = "Cures an ally of the pig status." },
            new Item() { contentId = 14, name = "Echo Herbs", type = "Item", description = "Cures an ally of silence." },
            new Item() { contentId = 15, name = "Eye Drops", type = "Item", description = "Cures an ally of darkness." },
            new Item() { contentId = 16, name = "Antidote", type = "Item", description = "Cures an ally of poison." },
            new Item() { contentId = 17, name = "Cross", type = "Item", description = "Cures an ally of a curse." },
            new Item() { contentId = 18, name = "Remedy", type = "Item", description = "Relieves all status ailments, but cannot revive a KO'd ally." },
            new Item() { contentId = 19, name = "Alarm Clock", type = "Item", description = "A timepiece that releases all allies from sleep." },
            new Item() { contentId = 20, name = "Unicorn Horn", type = "Item", description = "A horn that releases all allies from sleep, paralysis, confusion, and berserk." },
            new Item() { contentId = 21, name = "Tent", type = "Item", description = "Recovers the party's HP and MP. Can be used outdoors." },
            new Item() { contentId = 22, name = "Cottage", type = "Item", description = "Fully recovers the party's HP and MP. Can be used outdoors." },
            new Item() { contentId = 23, name = "Emergency Exit", type = "Item", description = "Allows you to escape instantly from a dungeon." },
            new Item() { contentId = 24, name = "Dwarven Bread", type = "Item", description = "Bread with the same effect as Sight." },
            new Item() { contentId = 25, name = "Gysahl Greens", type = "Item", description = "The favorite food of Fat Chocobo.\nTry using it where it smells of chocobo." },
            new Item() { contentId = 26, name = "Gysahl Whistle", type = "Item", description = "A whistle for calling Fat Chocobo." },
            new Item() { contentId = 27, name = "Golden Apple", type = "Item", description = "Increases maximum HP by 100." },
            new Item() { contentId = 28, name = "Silver Apple", type = "Item", description = "Increases maximum HP by 50." },
            new Item() { contentId = 29, name = "Soma Drop", type = "Item", description = "Increases maximum MP by 10." },
            new Item() { contentId = 30, name = "Siren", type = "Item", description = "An alarm that calls monsters." },
            new Item() { contentId = 33, name = "Red Fang", type = "Item", description = "A dragon fang that deals fire damage." },
            new Item() { contentId = 34, name = "White Fang", type = "Item", description = "A dragon fang that deals ice damage." },
            new Item() { contentId = 35, name = "Blue Fang", type = "Item", description = "A dragon fang that deals thunder damage." },
            new Item() { contentId = 36, name = "Bomb Fragment", type = "Item", description = "Has the same effect as Fire." },
            new Item() { contentId = 37, name = "Bomb Arm", type = "Item", description = "Has the same effect as Fira." },
            new Item() { contentId = 38, name = "Antarctic Wind", type = "Item", description = "A stone with the same effect as Blizzard." },
            new Item() { contentId = 39, name = "Arctic Wind", type = "Item", description = "A stone with the same effect as Blizzara." },
            new Item() { contentId = 40, name = "Zeus's Wrath", type = "Item", description = "A statue with the same effect as Thunder." },
            new Item() { contentId = 41, name = "Rage of the Gods", type = "Item", description = "A statue with the same effect as Thundara." },
            new Item() { contentId = 42, name = "Gaia Drum", type = "Item", description = "A drum with the same effect as Quake." },
            new Item() { contentId = 43, name = "Bomb Core", type = "Item", description = "Deals damage in exchange for the user's life." },
            new Item() { contentId = 44, name = "Stardust", type = "Item", description = "Sand with the same effect as Comet." },
            new Item() { contentId = 45, name = "Lilith's Kiss", type = "Item", description = "A statue with the same effect as Osmose." },
            new Item() { contentId = 46, name = "Vampire Fang", type = "Item", description = "A fang with the same effect as Drain." },
            new Item() { contentId = 47, name = "Spider's Silk", type = "Item", description = "Sticky thread with the same effect as Slow." },
            new Item() { contentId = 48, name = "Bell of Silence", type = "Item", description = "A bell with the same effect as Silence." },
            new Item() { contentId = 49, name = "Coeurl Whisker", type = "Item", description = "A whisker with the same effect as Death." },
            new Item() { contentId = 50, name = "Bestiary", type = "Item", description = "A compendium with the same effect as Scan." },
            new Item() { contentId = 51, name = "Hourglass", type = "Item", description = "A timepiece with the same effect as Stop." },
            new Item() { contentId = 52, name = "Silver Hourglass", type = "Item", description = "A timepiece with the same effect as Stop, but longer lasting." },
            new Item() { contentId = 53, name = "Gold Hourglass", type = "Item", description = "A timepiece with the same effect as Stop, but much longer lasting." },
            new Item() { contentId = 54, name = "Bacchus's Cider", type = "Item", description = "A drink with the same effect as Berserk." },
            new Item() { contentId = 55, name = "Hermes Shoes", type = "Item", description = "Shoes with the same effect as Haste." },
            new Item() { contentId = 56, name = "Decoy", type = "Item", description = "A doll with the same effect as Blink." },
            new Item() { contentId = 57, name = "Light Curtain", type = "Item", description = "A curtain with the same effect as Reflect." },
            new Item() { contentId = 58, name = "Lunar Curtain", type = "Item", description = "A curtain that nullifies attacks and casts Reflect." },
            new Item() { contentId = 59, name = "Crystal", type = "Item", description = "A crystal that emits holy light." },
            new Item() { contentId = 76, name = "Goblin", type = "Item", description = "Teaches (RYDIA) Goblin." },
            new Item() { contentId = 77, name = "Bomb", type = "Item", description = "Teaches (RYDIA) Bomb." },
            new Item() { contentId = 78, name = "Cockatrice", type = "Item", description = "Teaches (RYDIA) Cockatrice." },
            new Item() { contentId = 79, name = "Mind Flayer", type = "Item", description = "Teaches (RYDIA) Mind Flayer." },
            new Item() { contentId = 127, name = "Empty", type = "Weapon", description = "" },
            new Item() { contentId = 128, name = "Dark Sword", type = "Weapon", description = "A common dark sword." },
            new Item() { contentId = 129, name = "Shadowblade", type = "Weapon", description = "A dark sword with a sharpened blade." },
            new Item() { contentId = 130, name = "Deathbringer", type = "Weapon", description = "A dark sword that may cause instant death." },
            new Item() { contentId = 131, name = "Sword of Legend", type = "Weapon", description = "A holy sword inscribed with the legend of Mysidia." },
            new Item() { contentId = 132, name = "Light Sword", type = "Weapon", description = "A holy sword that shines with divine light." },
            new Item() { contentId = 133, name = "Excalibur", type = "Weapon", description = "The legendary holy sword of a hero." },
            new Item() { contentId = 134, name = "Ragnarok", type = "Weapon", description = "A holy sword feared by monsters that was once sealed." },
            new Item() { contentId = 135, name = "Ancient Sword", type = "Weapon", description = "A sword that may curse the enemy and is effective against ghouls." },
            new Item() { contentId = 136, name = "Blood Sword", type = "Weapon", description = "A sword that steals HP and is effective against giant and flan enemies." },
            new Item() { contentId = 137, name = "Mythril Sword", type = "Weapon", description = "A sword that is effective against ghouls." },
            new Item() { contentId = 138, name = "Sleep Blade", type = "Weapon", description = "A sword that may cast Sleep on the enemy." },
            new Item() { contentId = 139, name = "Flame Sword", type = "Weapon", description = "A sword imbued with the power of fire." },
            new Item() { contentId = 140, name = "Icebrand", type = "Weapon", description = "A sword imbued with the power of ice." },
            new Item() { contentId = 141, name = "Gorgon Blade", type = "Weapon", description = "A sword that may gradually petrify the enemy." },
            new Item() { contentId = 142, name = "Avenger", type = "Weapon", description = "A two-handed cursed sword that causes the berserk ailment." },
            new Item() { contentId = 143, name = "Defender", type = "Weapon", description = "A sword infused with protective power; casts Protect when used in battle." },
            new Item() { contentId = 148, name = "Spear", type = "Weapon", description = "A common spear." },
            new Item() { contentId = 149, name = "Wind Spear", type = "Weapon", description = "A spear with a keen blade." },
            new Item() { contentId = 150, name = "Fire Lance", type = "Weapon", description = "A spear imbued with the power of flame; casts Fire when used in battle." },
            new Item() { contentId = 151, name = "Ice Lance", type = "Weapon", description = "A spear imbued with the power of ice; casts Blizzara when used in battle." },
            new Item() { contentId = 152, name = "Blood Lance", type = "Weapon", description = "A spear that steals HP and is effective against giant and flan enemies." },
            new Item() { contentId = 153, name = "Gungnir", type = "Weapon", description = "A legendary spear favored by the gods." },
            new Item() { contentId = 154, name = "Wyvern Lance", type = "Weapon", description = "A spear that is effective against dragons." },
            new Item() { contentId = 155, name = "Holy Lance", type = "Weapon", description = "A spear imbued with sacred power; casts Holy when used in battle." },
            new Item() { contentId = 156, name = "Mythril Knife", type = "Weapon", description = "A knife that is effective against ghouls." },
            new Item() { contentId = 157, name = "Dancing Dagger", type = "Weapon", description = "A dagger infused with the might of a dancer." },
            new Item() { contentId = 158, name = "Mage Masher", type = "Weapon", description = "A knife that may cause silence and is effective against mages." },
            new Item() { contentId = 159, name = "Knife", type = "Weapon", description = "A kitchen knife that can cut anything." },
            new Item() { contentId = 160, name = "Dreamer's Harp", type = "Weapon", description = "A harp that weaves a lulling melody; may cause the enemy to fall asleep." },
            new Item() { contentId = 161, name = "Lamia's Harp", type = "Weapon", description = "A harp that weaves a tempting melody that may cause confusion." },
            new Item() { contentId = 162, name = "Fire Claw", type = "Weapon", description = "A claw imbued with the power of fire." },
            new Item() { contentId = 163, name = "Ice Claw", type = "Weapon", description = "A claw imbued with the power of ice." },
            new Item() { contentId = 164, name = "Thunder Claw", type = "Weapon", description = "A claw imbued with the power of lightning." },
            new Item() { contentId = 165, name = "Fairy Claw", type = "Weapon", description = "A claw that may cause confusion and is effective against giant enemies." },
            new Item() { contentId = 166, name = "Hell Claw", type = "Weapon", description = "A claw that may poison the enemy." },
            new Item() { contentId = 167, name = "Cat Claw", type = "Weapon", description = "A claw that may put the enemy to sleep." },
            new Item() { contentId = 168, name = "Wooden Hammer", type = "Weapon", description = "A wooden hammer that is effective against machines." },
            new Item() { contentId = 169, name = "Mythril Hammer", type = "Weapon", description = "A hammer that is effective against ghouls and machines." },
            new Item() { contentId = 170, name = "Gaia Hammer", type = "Weapon", description = "A fire hammer that is effective against machines; casts Quake when used in battle." },
            new Item() { contentId = 171, name = "Dwarven Axe", type = "Weapon", description = "A throwing axe commonly favored by dwarves." },
            new Item() { contentId = 172, name = "Ogrekiller", type = "Weapon", description = "A giant axe that is effective against giants." },
            new Item() { contentId = 173, name = "Poison Axe", type = "Weapon", description = "A two-handed axe that may cast Poison on the enemy." },
            new Item() { contentId = 174, name = "Rune Axe", type = "Weapon", description = "A two-handed axe that is effective against mages." },
            new Item() { contentId = 175, name = "Kunai", type = "Weapon", description = "A small katana used by ninjas." },
            new Item() { contentId = 176, name = "Ashura", type = "Weapon", description = "A katana named after the avatar of war." },
            new Item() { contentId = 177, name = "Kotetsu", type = "Weapon", description = "A short katana forged for ease of use." },
            new Item() { contentId = 178, name = "Kikuichimonji", type = "Weapon", description = "A katana with a chrysanthemum engraved on its sheath." },
            new Item() { contentId = 179, name = "Murasame", type = "Weapon", description = "A katana said to hide otherworldly power; casts Protect when used in battle." },
            new Item() { contentId = 180, name = "Masamune", type = "Weapon", description = "The most powerful katana in the land; casts Haste when used in battle." },
            new Item() { contentId = 181, name = "Rod", type = "Weapon", description = "A magical rod that casts Magic Arrow when used in battle." },
            new Item() { contentId = 182, name = "Flame Rod", type = "Weapon", description = "A rod infused with the power of fire; casts Fire when used in battle." },
            new Item() { contentId = 183, name = "Ice Rod", type = "Weapon", description = "A rod infused with the power of ice; casts Blizzard when used in battle." },
            new Item() { contentId = 184, name = "Thunder Rod", type = "Weapon", description = "A rod infused with the power of lightning; casts Thunder when used in battle." },
            new Item() { contentId = 185, name = "Lilith Rod", type = "Weapon", description = "A rod that absorbs HP; casts Osmose when used in battle." },
            new Item() { contentId = 186, name = "Rod of Change", type = "Weapon", description = "A rod infused with beastly rage; casts Pig when used in battle." },
            new Item() { contentId = 187, name = "Fairy Rod", type = "Weapon", description = "A rod infused with fairy magic; casts Confuse when used in battle." },
            new Item() { contentId = 188, name = "Stardust Rod", type = "Weapon", description = "A rod infused with the power of the stars; casts Comet when used in battle." },
            new Item() { contentId = 189, name = "Staff", type = "Weapon", description = "A staff infused with the power to detoxify; casts Poisona when used in battle." },
            new Item() { contentId = 190, name = "Healing Staff", type = "Weapon", description = "A staff that restores HP; casts Heal when used in battle." },
            new Item() { contentId = 191, name = "Mythril Staff", type = "Weapon", description = "A mythril staff that is effective against the undead; casts Basuna to cure certain status ailments." },
            new Item() { contentId = 192, name = "Power Staff", type = "Weapon", description = "A staff that may drive the enemy berserk." },
            new Item() { contentId = 193, name = "Kinesis Staff", type = "Weapon", description = "A staff that casts Dispel when used in battle." },
            new Item() { contentId = 194, name = "Sage's Staff", type = "Weapon", description = "A staff that casts Life when used in battle." },
            new Item() { contentId = 195, name = "Rune Staff", type = "Weapon", description = "A staff that casts Silence when used in battle." },
            new Item() { contentId = 196, name = "Bow", type = "Weapon", description = "A common bow." },
            new Item() { contentId = 198, name = "Great Bow", type = "Weapon", description = "A bow used in battle." },
            new Item() { contentId = 199, name = "Killer Bow", type = "Weapon", description = "A bow with increased capability for critical hits." },
            new Item() { contentId = 200, name = "Elven Bow", type = "Weapon", description = "A mage-slaying bow made by the elves; casts Shell when used in battle." },
            new Item() { contentId = 201, name = "Yoichi's Bow", type = "Weapon", description = "A bow that belonged to a famous marksman." },
            new Item() { contentId = 202, name = "Artemis's Bow", type = "Weapon", description = "A bow named after the goddess of the moon." },
            new Item() { contentId = 203, name = "Medusa Arrow", type = "Weapon", description = "An arrow that may petrify the enemy." },
            new Item() { contentId = 204, name = "Iron Arrow", type = "Weapon", description = "An arrow made of iron." },
            new Item() { contentId = 205, name = "Holy Arrow", type = "Weapon", description = "An arrow imbued with holy power." },
            new Item() { contentId = 206, name = "Fire Arrow", type = "Weapon", description = "An arrow imbued with the power of fire." },
            new Item() { contentId = 207, name = "Ice Arrow", type = "Weapon", description = "An arrow imbued with the power of ice." },
            new Item() { contentId = 208, name = "Thunder Arrow", type = "Weapon", description = "An arrow imbued with the power of lightning." },
            new Item() { contentId = 209, name = "Blinding Arrow", type = "Weapon", description = "An arrow that may envelop the enemy in darkness." },
            new Item() { contentId = 210, name = "Poison Arrow", type = "Weapon", description = "An arrow that may poison the enemy." },
            new Item() { contentId = 211, name = "Mute Arrow", type = "Weapon", description = "An arrow that may cause silence and is effective against mages." },
            new Item() { contentId = 212, name = "Angel Arrow", type = "Weapon", description = "An arrow that may cause confusion and is effective against giant enemies." },
            new Item() { contentId = 213, name = "Yoichi Arrow", type = "Weapon", description = "An arrow that belonged to a marksmen from a distant land." },
            new Item() { contentId = 214, name = "Artemis Arrow", type = "Weapon", description = "An arrow named after the goddess of the moon that is effective against dragons." },
            new Item() { contentId = 215, name = "Whip", type = "Weapon", description = "A common whip that may cause paralysis." },
            new Item() { contentId = 216, name = "Chain Whip", type = "Weapon", description = "An iron chain whip that may cause paralysis." },
            new Item() { contentId = 217, name = "Blitz Whip", type = "Weapon", description = "A lightning whip that may cause paralysis." },
            new Item() { contentId = 218, name = "Flame Whip", type = "Weapon", description = "A fire whip that may cause paralysis." },
            new Item() { contentId = 219, name = "Dragon's Whisker", type = "Weapon", description = "A dragon-slaying whip that may cause paralysis." },
            new Item() { contentId = 220, name = "Boomerang", type = "Weapon", description = "A wooden throwing weapon." },
            new Item() { contentId = 221, name = "Moonring Blade", type = "Weapon", description = "A metal throwing weapon." },
            new Item() { contentId = 222, name = "Shuriken", type = "Weapon", description = "A weapon thrown by ninjas." },
            new Item() { contentId = 223, name = "Fuma Shuriken", type = "Weapon", description = "A weapon thrown by ninjas." },
            new Item() { contentId = 224, name = "None", type = "Armor - Shield", description = "" },
            new Item() { contentId = 225, name = "None", type = "Armor - Body", description = "" },
            new Item() { contentId = 226, name = "None", type = "Armor - Head", description = "" },
            new Item() { contentId = 227, name = "None", type = "Armor - Arms", description = "" },
            new Item() { contentId = 228, name = "Iron Shield", type = "Armor - Shield", description = "A shield made of iron." },
            new Item() { contentId = 229, name = "Dark Shield", type = "Armor - Shield", description = "A shield possessing a powerful dark force." },
            new Item() { contentId = 230, name = "Demon Shield", type = "Armor - Shield", description = "A shield said to have once belonged to a demon." },
            new Item() { contentId = 231, name = "Light Shield", type = "Armor - Shield", description = "A shield that is resistant to undead attacks." },
            new Item() { contentId = 232, name = "Mythril Shield", type = "Armor - Shield", description = "A shield that is resistant to ghoul attacks." },
            new Item() { contentId = 233, name = "Flame Shield", type = "Armor - Shield", description = "A shield imbued with the power of fire, that is resistant to ice and weak to fire." },
            new Item() { contentId = 234, name = "Ice Shield", type = "Armor - Shield", description = "A shield imbued with the power of ice, that is resistant to fire and weak to ice." },
            new Item() { contentId = 235, name = "Diamond Shield", type = "Armor - Shield", description = "A shield that is resistant to lightning." },
            new Item() { contentId = 236, name = "Aegis Shield", type = "Armor - Shield", description = "A shield that is resistant to mage attacks and prevents petrification." },
            new Item() { contentId = 237, name = "Genji Shield", type = "Armor - Shield", description = "A shield that was once used in a faraway land." },
            new Item() { contentId = 238, name = "Dragon Shield", type = "Armor - Shield", description = "A shield that is resistant to dragon attacks, fire, ice, and lightning." },
            new Item() { contentId = 239, name = "Crystal Shield", type = "Armor - Shield", description = "A shield that is resistant to undead attacks." },
            new Item() { contentId = 241, name = "Leather Cap", type = "Armor - Head", description = "A cap made of leather." },
            new Item() { contentId = 242, name = "Headband", type = "Armor - Head", description = "A cloth band that prevents confusion." },
            new Item() { contentId = 243, name = "Feathered Cap", type = "Armor - Head", description = "A light cap made from silk thread." },
            new Item() { contentId = 244, name = "Iron Helm", type = "Armor - Head", description = "A helmet made of iron." },
            new Item() { contentId = 245, name = "Wizard's Hat", type = "Armor - Head", description = "A cap made from special thread." },
            new Item() { contentId = 246, name = "Green Beret", type = "Armor - Head", description = "A cap that is full of magic power." },
            new Item() { contentId = 247, name = "Dark Helm", type = "Armor - Head", description = "A helmet possessing a powerful dark force." },
            new Item() { contentId = 248, name = "Hades Helm", type = "Armor - Head", description = "A helmet said to have once belonged to a demon." },
            new Item() { contentId = 249, name = "Sage's Miter", type = "Armor - Head", description = "A cap that is resistant to undead attacks and made from sacred thread." },
            new Item() { contentId = 250, name = "Black Cowl", type = "Armor - Head", description = "A hood that prevents sleep." },
            new Item() { contentId = 251, name = "Demon Helm", type = "Armor - Head", description = "A helmet said to be possessed by a demon." },
            new Item() { contentId = 252, name = "Light Helm", type = "Armor - Head", description = "A helmet that is resistant to undead attacks." },
            new Item() { contentId = 253, name = "Gold Hairpin", type = "Armor - Head", description = "A hairpin that is resistant to undead attacks and lightning." },
            new Item() { contentId = 254, name = "Mythril Helm", type = "Armor - Head", description = "A helmet that is resistant to ghoul attacks." },
            new Item() { contentId = 255, name = "Diamond Helm", type = "Armor - Head", description = "A helmet that is resistant to lightning." },
            new Item() { contentId = 256, name = "Ribbon", type = "Armor - Head", description = "A ribbon that is resistant to mage attacks and prevents various status ailments." },
            new Item() { contentId = 257, name = "Genji Helm", type = "Armor - Head", description = "A helmet that was once used in a faraway land." },
            new Item() { contentId = 258, name = "Dragon Helm", type = "Armor - Head", description = "A helmet that is resistant to dragon attacks, fire, ice, and lightning." },
            new Item() { contentId = 259, name = "Crystal Helm", type = "Armor - Head", description = "A helmet that is resistant to undead attacks, fire, ice, and lightning." },
            new Item() { contentId = 260, name = "Glass Mask", type = "Armor - Head", description = "A mask made of glass." },
            new Item() { contentId = 262, name = "Clothes", type = "Armor - Body", description = "A set of common clothes." },
            new Item() { contentId = 263, name = "Prisoners' Wear", type = "Armor - Body", description = "Clothes that prevent sleep." },
            new Item() { contentId = 264, name = "Leather Garb", type = "Armor - Body", description = "Clothes made of leather." },
            new Item() { contentId = 265, name = "Bard's Tunic", type = "Armor - Body", description = "Clothes that prevent silence." },
            new Item() { contentId = 266, name = "Gaia Gear", type = "Armor - Body", description = "Clothes that prevent gradual petrification." },
            new Item() { contentId = 267, name = "Iron Armor", type = "Armor - Body", description = "Armor made of iron." },
            new Item() { contentId = 268, name = "Dark Armor", type = "Armor - Body", description = "Armor possessing a powerful dark force." },
            new Item() { contentId = 269, name = "Sage's Surplice", type = "Armor - Body", description = "A robe made from sacred thread." },
            new Item() { contentId = 270, name = "Kenpo Gi", type = "Armor - Body", description = "Clothes favored by martial artists." },
            new Item() { contentId = 271, name = "Hades Armor", type = "Armor - Body", description = "Armor said to have once belonged to a demon." },
            new Item() { contentId = 272, name = "Black Robe", type = "Armor - Body", description = "A robe made for those who use black magic." },
            new Item() { contentId = 273, name = "Demon Armor", type = "Armor - Body", description = "Armor said to be possessed by a demon." },
            new Item() { contentId = 274, name = "Black Belt Gi", type = "Armor - Body", description = "Light and comfortable clothes from a faraway land." },
            new Item() { contentId = 275, name = "Knight's Armor", type = "Armor - Body", description = "Armor that is resistant to undead attacks." },
            new Item() { contentId = 276, name = "Light Robe", type = "Armor - Body", description = "A robe that is resistant to undead attacks and lightning." },
            new Item() { contentId = 277, name = "Mythril Armor", type = "Armor - Body", description = "Armor that is resistant to ghoul attacks." },
            new Item() { contentId = 278, name = "Flame Mail", type = "Armor - Body", description = "Armor imbued with the power of fire, that is resistant to ice and weak to fire." },
            new Item() { contentId = 279, name = "Power Sash", type = "Armor - Body", description = "A sash made from special thread." },
            new Item() { contentId = 280, name = "Ice Armor", type = "Armor - Body", description = "Armor imbued with the power of ice, that is resistant to fire and weak to ice." },
            new Item() { contentId = 281, name = "White Robe", type = "Armor - Body", description = "A darkness-resistant robe made for those who use white magic." },
            new Item() { contentId = 282, name = "Diamond Armor", type = "Armor - Body", description = "Armor that is resistant to lightning." },
            new Item() { contentId = 283, name = "Minerva Bustier", type = "Armor - Body", description = "Paralysis-resistant clothes worn by the goddess of the heavens." },
            new Item() { contentId = 284, name = "Genji Armor", type = "Armor - Body", description = "Armor that was once used in a faraway land." },
            new Item() { contentId = 285, name = "Dragon Mail", type = "Armor - Body", description = "Armor that is resistant to dragon attacks, fire, ice, and lightning." },
            new Item() { contentId = 286, name = "Black Garb", type = "Armor - Body", description = "An entirely black outfit brought from a faraway land." },
            new Item() { contentId = 287, name = "Crystal Mail", type = "Armor - Body", description = "Armor that is resistant to undead attacks and prevents various status ailments." },
            new Item() { contentId = 288, name = "Adamant Armor", type = "Armor - Body", description = "Adamantite armor that prevents various status ailments and is resistant to fire, ice, and lightning." },
            new Item() { contentId = 290, name = "Ruby Ring", type = "Armor - Arms", description = "A ring that prevents the pig status." },
            new Item() { contentId = 291, name = "Cursed Ring", type = "Armor - Arms", description = "A ring that enhances elemental resistance." },
            new Item() { contentId = 292, name = "Iron Gloves", type = "Armor - Arms", description = "Gloves made of iron." },
            new Item() { contentId = 293, name = "Dark Gloves", type = "Armor - Arms", description = "Gloves possessing a powerful dark force." },
            new Item() { contentId = 294, name = "Iron Armlet", type = "Armor - Arms", description = "An armlet made of iron." },
            new Item() { contentId = 295, name = "Power Armlet", type = "Armor - Arms", description = "A wristband that increases a martial artist's power." },
            new Item() { contentId = 296, name = "Hades Gloves", type = "Armor - Arms", description = "Gloves said to have once belonged to a demon." },
            new Item() { contentId = 297, name = "Demon Gloves", type = "Armor - Arms", description = "Gloves said to be possessed by a demon." },
            new Item() { contentId = 298, name = "Silver Armlet", type = "Armor - Arms", description = "An armlet that is resistant to ghoul attacks." },
            new Item() { contentId = 299, name = "Gauntlets", type = "Armor - Arms", description = "Gloves that are resistant to undead attacks." },
            new Item() { contentId = 300, name = "Rune Armlet", type = "Armor - Arms", description = "An armlet that is resistant to mage attacks and prevents silence." },
            new Item() { contentId = 301, name = "Mythril Gloves", type = "Armor - Arms", description = "Gloves that are resistant to ghoul attacks." },
            new Item() { contentId = 302, name = "Diamond Armlet", type = "Armor - Arms", description = "An armlet that is resistant to lightning." },
            new Item() { contentId = 303, name = "Diamond Gloves", type = "Armor - Arms", description = "Gloves that are resistant to lightning." },
            new Item() { contentId = 304, name = "Genji Gloves", type = "Armor - Arms", description = "Gloves that were once used in a faraway land." },
            new Item() { contentId = 305, name = "Dragon Gloves", type = "Armor - Arms", description = "Gloves that are resistant to dragon attacks, fire, ice, and lightning." },
            new Item() { contentId = 306, name = "Giant's Gloves", type = "Armor - Arms", description = "Gloves that are resistant to giant enemies and prevent mini." },
            new Item() { contentId = 307, name = "Crystal Gloves", type = "Armor - Arms", description = "Gloves that are resistant to undead attacks." },
            new Item() { contentId = 308, name = "Protect Ring", type = "Armor - Arms", description = "A ring that is resistant to fire, ice, and lightning." },
            new Item() { contentId = 309, name = "Crystal Ring", type = "Armor - Arms", description = "A ring that is resistant to dragon attacks and prevents confusion, sleep, and paralysis." },
            new Item() { contentId = 520, name = "Grimoire", type = "Item", description = "A book that summons a monster.\nYou won't know which until you try it!" },
            new Item() { contentId = 521, name = "Crossbow", type = "Weapon", description = "A bow used for hunting." },
        };

        // TODOX No items for FF5 yet
        public static List<Item> FF5Items = new List<Item>() {
        };

        public static List<Item> FF6Items = new List<Item>() {
            new Item() { contentId = 2, name = "Potion", type = "Item", description = "Restores 50 HP." },
            new Item() { contentId = 3, name = "Hi-Potion", type = "Item", description = "Restores 250 HP." },
            new Item() { contentId = 4, name = "X-Potion", type = "Item", description = "Fully restores HP." },
            new Item() { contentId = 5, name = "Ether", type = "Item", description = "Restores 50 MP." },
            new Item() { contentId = 6, name = "Hi-Ether", type = "Item", description = "Restores 150 MP." },
            new Item() { contentId = 7, name = "X-Ether", type = "Item", description = "Fully restores MP." },
            new Item() { contentId = 8, name = "Elixir", type = "Item", description = "Fully restores HP and MP." },
            new Item() { contentId = 9, name = "Megalixir", type = "Item", description = "Fully restores the entire party's HP and MP." },
            new Item() { contentId = 10, name = "Phoenix Down", type = "Item", description = "Cures the KO status." },
            new Item() { contentId = 11, name = "Holy Water", type = "Item", description = "Cures the zombie status." },
            new Item() { contentId = 12, name = "Antidote", type = "Item", description = "Cures poison." },
            new Item() { contentId = 13, name = "Eye Drops", type = "Item", description = "Cures darkness." },
            new Item() { contentId = 14, name = "Gold Needle", type = "Item", description = "Cures petrification." },
            new Item() { contentId = 15, name = "Remedy", type = "Item", description = "Cures the status ailments of petrification, imp, silence, darkness, sap, and poison." },
            new Item() { contentId = 16, name = "Sleeping Bag", type = "Item", description = "Fully restores one person's HP and MP. Can be used outdoors." },
            new Item() { contentId = 17, name = "Tent", type = "Item", description = "Fully restores the entire party's HP and MP. Can be used outdoors." },
            new Item() { contentId = 18, name = "Green Cherry", type = "Item", description = "Cures the imp status." },
            new Item() { contentId = 19, name = "Magicite Shard", type = "Item", description = "Summons a random Esper. May even summon Espers not in the party's possession." },
            new Item() { contentId = 20, name = "Super Ball", type = "Item", description = "Bounces around the battlefield when thrown. Deals damage to all enemies." },
            new Item() { contentId = 21, name = "Echo Screen", type = "Item", description = "Cures silence." },
            new Item() { contentId = 22, name = "Smoke Bomb", type = "Item", description = "Releases a cloud of thick smoke when thrown. Allows the party to escape from battle." },
            new Item() { contentId = 23, name = "Teleport Stone", type = "Item", description = "Enchanted with the Teleport spell. Removes the party from a dungeon or battle." },
            new Item() { contentId = 24, name = "Dried Meat", type = "Item", description = "Cures an empty stomach." },
            new Item() { contentId = 25, name = "Rename Card", type = "Item", description = "A secret item. Allows one ally to change their name." },
            new Item() { contentId = 26, name = "Flame Scroll", type = "Item", description = "Deals fire damage to all enemies. Use with the Throw command." },
            new Item() { contentId = 27, name = "Water Scroll", type = "Item", description = "Deals water damage to all enemies. Use with the Throw command." },
            new Item() { contentId = 28, name = "Lightning Scroll", type = "Item", description = "Deals lightning damage to all enemies. Use with the Throw command." },
            new Item() { contentId = 29, name = "Invisibility Scroll", type = "Item", description = "Grants invisibility to the thrower. Use with the Throw command." },
            new Item() { contentId = 30, name = "Shadow Scroll", type = "Item", description = "Creates illusionary images of the thrower. Use with the Throw command." },
            new Item() { contentId = 31, name = "Noiseblaster", type = "Item", description = "Confuses all enemies with a blast of sound. Use with the Tools command." },
            new Item() { contentId = 32, name = "Bioblaster", type = "Item", description = "Attacks and inflicts poison damage to all enemies. Use with the Tools command." },
            new Item() { contentId = 33, name = "Flash", type = "Item", description = "Attacks and inflicts darkness on all enemies. Use with the Tools command." },
            new Item() { contentId = 34, name = "Chainsaw", type = "Item", description = "Damages or instantly dispatches an enemy. Use with the Tools command." },
            new Item() { contentId = 35, name = "Debilitator", type = "Item", description = "Assigns a random elemental weakness to an enemy. Use with the Tools command." },
            new Item() { contentId = 36, name = "Drill", type = "Item", description = "Penetrates an enemy's armor to deal severe damage. Use with the Tools command." },
            new Item() { contentId = 37, name = "Air Anchor", type = "Item", description = "Causes an enemy to self-destruct upon moving. Use with the Tools command." },
            new Item() { contentId = 38, name = "Auto Crossbow", type = "Item", description = "Strikes all enemies with a spray of crossbow bolts. Use with the Tools command." },
            new Item() { contentId = 93, name = "Empty", type = "Weapon", description = "" },
            new Item() { contentId = 94, name = "Dagger", type = "Weapon", description = "A light and well-balanced dagger." },
            new Item() { contentId = 95, name = "Mythril Knife", type = "Weapon", description = "A sturdy adventurer's knife forged from pure mythril." },
            new Item() { contentId = 96, name = "Main Gauche", type = "Weapon", description = "A short dagger that sometimes parries enemy attacks." },
            new Item() { contentId = 97, name = "Air Knife", type = "Weapon", description = "A knife imbued with the power of wind." },
            new Item() { contentId = 98, name = "Thief's Knife", type = "Weapon", description = "A knife that sometimes steals from an enemy." },
            new Item() { contentId = 99, name = "Assassin's Dagger", type = "Weapon", description = "A blade that may randomly dispatch an enemy in one hit." },
            new Item() { contentId = 100, name = "Man-Eater", type = "Weapon", description = "A dagger that is especially effective against humanoids." },
            new Item() { contentId = 101, name = "Swordbreaker", type = "Weapon", description = "A shortsword that sometimes parries enemy attacks." },
            new Item() { contentId = 102, name = "Gladius", type = "Weapon", description = "A dagger blessed with the power to smite evil foes." },
            new Item() { contentId = 103, name = "Valiant Knife", type = "Weapon", description = "A knife that grows in power as its wielder's HP dwindles." },
            new Item() { contentId = 104, name = "Mythril Sword", type = "Weapon", description = "A simple sword forged from mythril." },
            new Item() { contentId = 105, name = "Great Sword", type = "Weapon", description = "A heavy sword with a thick, broad blade." },
            new Item() { contentId = 106, name = "Rune Blade", type = "Weapon", description = "A sword that draws MP from its wielder to deal critical hits." },
            new Item() { contentId = 107, name = "Flametongue", type = "Weapon", description = "A sword infused with the power of flame that may cast Fire upon striking an enemy." },
            new Item() { contentId = 108, name = "Icebrand", type = "Weapon", description = "A sword infused with the power of ice that may cast Blizzard upon striking an enemy." },
            new Item() { contentId = 109, name = "Thunder Blade", type = "Weapon", description = "A sword infused with the power of lightning that may cast Thunder upon striking an enemy." },
            new Item() { contentId = 110, name = "Bastard Sword", type = "Weapon", description = "A sword with a long, narrow blade made for thrusting." },
            new Item() { contentId = 111, name = "Stoneblade", type = "Weapon", description = "A sword that may cast Break upon striking an enemy." },
            new Item() { contentId = 112, name = "Blood Sword", type = "Weapon", description = "A sword that absorbs HP from its victims." },
            new Item() { contentId = 113, name = "Enhancer", type = "Weapon", description = "A sword that boosts its wielder's magic." },
            new Item() { contentId = 114, name = "Crystal Sword", type = "Weapon", description = "A glittering blade cut from an enormous crystal shard." },
            new Item() { contentId = 115, name = "Falchion", type = "Weapon", description = "A single-edged sword that sometimes parries enemy attacks." },
            new Item() { contentId = 116, name = "Soul Saber", type = "Weapon", description = "A sword that drains MP and may cast Death upon striking an enemy." },
            new Item() { contentId = 117, name = "Organyx", type = "Weapon", description = "A knight's living blade that draws MP from its wielder to deal critical hits. May break upon use." },
            new Item() { contentId = 118, name = "Excalibur", type = "Weapon", description = "The legendary holy sword." },
            new Item() { contentId = 119, name = "Zantetsuken", type = "Weapon", description = "A sword that may randomly dispatch an enemy in one hit." },
            new Item() { contentId = 120, name = "Lightbringer", type = "Weapon", description = "A legendary sword of the heavens that may cast Holy upon striking an enemy. Uses up MP to deal a critical hit." },
            new Item() { contentId = 121, name = "Ragnarok", type = "Weapon", description = "A sword that may cast Flare upon striking an enemy. Uses up MP to deal a critical hit." },
            new Item() { contentId = 122, name = "Ultima Weapon", type = "Weapon", description = "A sword whose attack power is bound to its wielder's HP." },
            new Item() { contentId = 123, name = "Mythril Spear", type = "Weapon", description = "A simple spear forged from mythril." },
            new Item() { contentId = 124, name = "Trident", type = "Weapon", description = "A three-pronged military spear infused with the power of water." },
            new Item() { contentId = 125, name = "Heavy Lance", type = "Weapon", description = "A heavy lance used primarily by mounted soldiers." },
            new Item() { contentId = 126, name = "Partisan", type = "Weapon", description = "An ornate spear tipped with a twin-headed axe blade." },
            new Item() { contentId = 127, name = "Holy Lance", type = "Weapon", description = "A blessed lance that may cast Holy upon striking an enemy." },
            new Item() { contentId = 128, name = "Golden Spear", type = "Weapon", description = "A decorative spear with a golden tip." },
            new Item() { contentId = 129, name = "Radiant Lance", type = "Weapon", description = "A mighty spear that glows with an inner light." },
            new Item() { contentId = 130, name = "Impartisan", type = "Weapon", description = "A crude, crescent-tipped fishing spear used by imps." },
            new Item() { contentId = 131, name = "Kunai", type = "Weapon", description = "A basic ninja dagger with a straight blade." },
            new Item() { contentId = 132, name = "Kodachi", type = "Weapon", description = "A lightweight ninja sword with a medium-length blade." },
            new Item() { contentId = 133, name = "Sakura", type = "Weapon", description = "A ninja sword imbued with the power of wind." },
            new Item() { contentId = 134, name = "Sasuke", type = "Weapon", description = "A blade thought to have belonged to a famous ninja." },
            new Item() { contentId = 135, name = "Ichigeki", type = "Weapon", description = "A ninja sword that may randomly dispatch an enemy in one hit." },
            new Item() { contentId = 136, name = "Kagenui", type = "Weapon", description = "A ninja sword that may cast Stop upon striking an enemy." },
            new Item() { contentId = 137, name = "Ashura", type = "Weapon", description = "A katana named for an avatar of war." },
            new Item() { contentId = 138, name = "Kotetsu", type = "Weapon", description = "A modest katana designed for ease of use." },
            new Item() { contentId = 139, name = "Kikuichimonji", type = "Weapon", description = "An elegant katana with a chrysanthemum motif engraved on the scabbard." },
            new Item() { contentId = 140, name = "Kazekiri", type = "Weapon", description = "A sword infused with the power of wind that may invoke a cutting gale upon striking an enemy." },
            new Item() { contentId = 141, name = "Murasame", type = "Weapon", description = "A dancing blade that sometimes parries enemy attacks." },
            new Item() { contentId = 142, name = "Masamune", type = "Weapon", description = "A katana forged by a master swordsmith." },
            new Item() { contentId = 143, name = "Murakumo", type = "Weapon", description = "An ancient Doman blade that was lost during the War of the Magi." },
            new Item() { contentId = 144, name = "Mutsunokami", type = "Weapon", description = "A mysterious katana that sometimes parries enemy attacks." },
            new Item() { contentId = 145, name = "Healing Rod", type = "Weapon", description = "A rod that restores HP to whomever it taps." },
            new Item() { contentId = 146, name = "Mythril Rod", type = "Weapon", description = "A plain rod forged from mythril." },
            new Item() { contentId = 147, name = "Flame Rod", type = "Weapon", description = "A rod that may cast Fira upon striking an enemy. Casts Fira when used as an item and then breaks." },
            new Item() { contentId = 148, name = "Ice Rod", type = "Weapon", description = "A rod that may cast Blizzara upon striking an enemy. Casts Blizzara when used as an item and then breaks." },
            new Item() { contentId = 149, name = "Thunder Rod", type = "Weapon", description = "A rod that may cast Thundara upon striking an enemy. Casts Thundara when used as an item and then breaks." },
            new Item() { contentId = 150, name = "Poison Rod", type = "Weapon", description = "A rod that may cast Poison upon striking an enemy. Casts Poison when used as an item and then breaks." },
            new Item() { contentId = 151, name = "Holy Rod", type = "Weapon", description = "A rod that may cast Holy upon striking an enemy. Casts Holy when used as an item and then breaks." },
            new Item() { contentId = 152, name = "Gravity Rod", type = "Weapon", description = "A rod that may cast Graviga upon striking an enemy. Casts Graviga when used as an item and then breaks." },
            new Item() { contentId = 153, name = "Punisher", type = "Weapon", description = "A rod that draws MP from its wielder to deal critical hits." },
            new Item() { contentId = 154, name = "Magus Rod", type = "Weapon", description = "A rod that boosts its wielder's magic." },
            new Item() { contentId = 155, name = "Chocobo Brush", type = "Weapon", description = "A vintage paintbrush." },
            new Item() { contentId = 156, name = "Da Vinci Brush", type = "Weapon", description = "A standard artist's paintbrush." },
            new Item() { contentId = 157, name = "Magical Brush", type = "Weapon", description = "A paintbrush that enhances its user's abilities." },
            new Item() { contentId = 158, name = "Rainbow Brush", type = "Weapon", description = "A paintbrush with a beautifully patterned handle." },
            new Item() { contentId = 159, name = "Shuriken", type = "Weapon", description = "A four-pointed ninja throwing star. Use with the Throw command." },
            new Item() { contentId = 160, name = "Fuma Shuriken", type = "Weapon", description = "A five-pointed ninja throwing star. Use with the Throw command." },
            new Item() { contentId = 161, name = "Pinwheel", type = "Weapon", description = "A pinwheel with sharp, cutting blades. Use with the Throw command." },
            new Item() { contentId = 162, name = "Chain Flail", type = "Weapon", description = "A spiked steel ball connected by chain to a handle." },
            new Item() { contentId = 163, name = "Moonring Blade", type = "Weapon", description = "A steel throwing ring with a sharpened outer edge." },
            new Item() { contentId = 164, name = "Morning Star", type = "Weapon", description = "A weapon with a heavy steel ball at the end of its chain." },
            new Item() { contentId = 165, name = "Boomerang", type = "Weapon", description = "A curved throwing weapon carved from wood." },
            new Item() { contentId = 166, name = "Rising Sun", type = "Weapon", description = "A steel throwing ring with a serrated outer edge." },
            new Item() { contentId = 167, name = "Hawkeye", type = "Weapon", description = "A versatile weapon that can be swung or thrown. Effective against flying enemies." },
            new Item() { contentId = 168, name = "Bone Club", type = "Weapon", description = "A bone club covered in beautiful engravings." },
            new Item() { contentId = 169, name = "Sniper", type = "Weapon", description = "A throwing weapon that can also be held and swung. Effective against flying enemies." },
            new Item() { contentId = 170, name = "Wing Edge", type = "Weapon", description = "A boomerang that may randomly dispatch an enemy in one hit." },
            new Item() { contentId = 171, name = "Cards", type = "Weapon", description = "A deck of playing cards sporting the mark of a casino." },
            new Item() { contentId = 172, name = "Darts", type = "Weapon", description = "Darts modified for use as weapons." },
            new Item() { contentId = 173, name = "Death Tarot", type = "Weapon", description = "Cards that may cast Death upon striking an enemy." },
            new Item() { contentId = 174, name = "Viper Darts", type = "Weapon", description = "Darts that may randomly dispatch an enemy in one hit." },
            new Item() { contentId = 175, name = "Dice", type = "Weapon", description = "A pair of dice that deal more damage the higher number they roll." },
            new Item() { contentId = 176, name = "Fixed Dice", type = "Weapon", description = "A trio of dice that deal more damage the higher number they roll." },
            new Item() { contentId = 177, name = "Metal Knuckles", type = "Weapon", description = "Iron knuckles that put extra weight behind a punch." },
            new Item() { contentId = 178, name = "Mythril Claws", type = "Weapon", description = "Fighting claws forged from mythril." },
            new Item() { contentId = 179, name = "Kaiser Knuckles", type = "Weapon", description = "Spiked knuckles blessed with the power to smite evil." },
            new Item() { contentId = 180, name = "Venom Claws", type = "Weapon", description = "Iron claws infused with venom that may cast Poison upon striking an enemy." },
            new Item() { contentId = 181, name = "Burning Fist", type = "Weapon", description = "Knuckle infused with the power of flames that may cast Fire upon striking an enemy." },
            new Item() { contentId = 182, name = "Dragon Claws", type = "Weapon", description = "Knuckles mounted with dragon talons and infused with sacred power." },
            new Item() { contentId = 183, name = "Tigerfang", type = "Weapon", description = "Long fighting claws sharpened to a razor's edge." },
            new Item() { contentId = 197, name = "None", type = "Armor - Shield", description = "" },
            new Item() { contentId = 198, name = "None", type = "Armor - Body", description = "" },
            new Item() { contentId = 199, name = "None", type = "Armor - Head", description = "" },
            new Item() { contentId = 200, name = "None", type = "Armor - Relic", description = "" },
            new Item() { contentId = 201, name = "Buckler", type = "Armor - Shield", description = "A lightweight shield of simple construction." },
            new Item() { contentId = 202, name = "Heavy Shield", type = "Armor - Shield", description = "A large, sturdy shield made of steel." },
            new Item() { contentId = 203, name = "Mythril Shield", type = "Armor - Shield", description = "An elegant and lightweight shield forged from mythril." },
            new Item() { contentId = 204, name = "Golden Shield", type = "Armor - Shield", description = "A brilliant shield made of solid gold." },
            new Item() { contentId = 205, name = "Aegis Shield", type = "Armor - Shield", description = "A powerful shield that sometimes repels magic attacks." },
            new Item() { contentId = 206, name = "Diamond Shield", type = "Armor - Shield", description = "A baroque shield inlaid with large diamonds." },
            new Item() { contentId = 207, name = "Flame Shield", type = "Armor - Shield", description = "A shield that absorbs flame attacks. Casts Firaga when used as an item and then breaks." },
            new Item() { contentId = 208, name = "Ice Shield", type = "Armor - Shield", description = "A shield that absorbs ice attacks. Casts Blizzaga when used as an item and then breaks." },
            new Item() { contentId = 209, name = "Thunder Shield", type = "Armor - Shield", description = "A shield that absorbs lightning attacks. Casts Thundaga when used as an item and then breaks." },
            new Item() { contentId = 210, name = "Crystal Shield", type = "Armor - Shield", description = "A glimmering shield cut from a single, enormous crystal." },
            new Item() { contentId = 211, name = "Genji Shield", type = "Armor - Shield", description = "An ancient shield from a foreign land." },
            new Item() { contentId = 212, name = "Tortoise Shield", type = "Armor - Shield", description = "A crude turtle shell shield used by imps." },
            new Item() { contentId = 213, name = "Cursed Shield", type = "Armor - Shield", description = "A bloodstained shield that inflicts various status ailments upon the bearer." },
            new Item() { contentId = 214, name = "Paladin's Shield", type = "Armor - Shield", description = "A wondrous shield that blocks a variety of attacks." },
            new Item() { contentId = 215, name = "Force Shield", type = "Armor - Shield", description = "A shield that halves damage from multiple elements. Automatically casts Shell on the wearer." },
            new Item() { contentId = 216, name = "Leather Cap", type = "Armor - Head", description = "A lightweight cap made of stitched leather." },
            new Item() { contentId = 217, name = "Hairband", type = "Armor - Head", description = "A ladies' hairband." },
            new Item() { contentId = 218, name = "Plumed Hat", type = "Armor - Head", description = "A silk hat adorned with a flashy chocobo plume." },
            new Item() { contentId = 219, name = "Beret", type = "Armor - Head", description = "A cap that increases the success rate of the Sketch command." },
            new Item() { contentId = 220, name = "Magus Hat", type = "Armor - Head", description = "A conical hat made from cloth with magical properties." },
            new Item() { contentId = 221, name = "Bandana", type = "Armor - Head", description = "A durable bandana woven from behemoth hair." },
            new Item() { contentId = 222, name = "Iron Helm", type = "Armor - Head", description = "A heavy iron helm." },
            new Item() { contentId = 223, name = "Hypno Crown", type = "Armor - Head", description = "A crown that raises the success rate of the Control command." },
            new Item() { contentId = 224, name = "Priest's Miter", type = "Armor - Head", description = "A hat that raises maximum MP by 1/8." },
            new Item() { contentId = 225, name = "Green Beret", type = "Armor - Head", description = "A cap that raises maximum HP by 1/8." },
            new Item() { contentId = 226, name = "Twist Headband", type = "Armor - Head", description = "A headband often worn by martial artists." },
            new Item() { contentId = 227, name = "Mythril Helm", type = "Armor - Head", description = "A light but strong helm forged from mythril." },
            new Item() { contentId = 228, name = "Tiara", type = "Armor - Head", description = "A ladies' tiara that provides a boost to magic." },
            new Item() { contentId = 229, name = "Golden Helm", type = "Armor - Head", description = "A tough steel helm plated with brilliant gold." },
            new Item() { contentId = 230, name = "Tiger Mask", type = "Armor - Head", description = "A mask shaped like a roaring tiger's head." },
            new Item() { contentId = 231, name = "Red Cap", type = "Armor - Head", description = "A cap that provides a 25% bonus to maximum HP." },
            new Item() { contentId = 232, name = "Mystery Veil", type = "Armor - Head", description = "A veil worn by female dancers." },
            new Item() { contentId = 233, name = "Circlet", type = "Armor - Head", description = "A metal band that boosts the wearer's attributes." },
            new Item() { contentId = 234, name = "Royal Crown", type = "Armor - Head", description = "A crown that can only be worn by those of royal blood." },
            new Item() { contentId = 235, name = "Diamond Helm", type = "Armor - Head", description = "A helm studded with diamonds of exceptional hardness." },
            new Item() { contentId = 236, name = "Black Cowl", type = "Armor - Head", description = "A jet-black hood from a distant land." },
            new Item() { contentId = 237, name = "Crystal Helm", type = "Armor - Head", description = "A helm constructed of fused crystal shards." },
            new Item() { contentId = 238, name = "Oath Veil", type = "Armor - Head", description = "A bridal veil of purest white lace." },
            new Item() { contentId = 239, name = "Cat-Ear Hood", type = "Armor - Head", description = "A hood that halves damage from multiple elements. Doubles the gil obtained after battle." },
            new Item() { contentId = 240, name = "Genji Helm", type = "Armor - Head", description = "An exotic helm from a foreign land." },
            new Item() { contentId = 241, name = "Thornlet", type = "Armor - Head", description = "A cursed crown that gradually drains the wearer's HP." },
            new Item() { contentId = 242, name = "Saucer", type = "Armor - Head", description = "A shallow saucer often seen on the heads of imps." },
            new Item() { contentId = 244, name = "Leather Armor", type = "Armor - Body", description = "Armor made of hardened leather." },
            new Item() { contentId = 245, name = "Cotton Robe", type = "Armor - Body", description = "A robe of multilayered cotton." },
            new Item() { contentId = 246, name = "Kenpo Gi", type = "Armor - Body", description = "A martial arts uniform that offers excellent mobility." },
            new Item() { contentId = 247, name = "Iron Armor", type = "Armor - Body", description = "A suit of heavy iron armor." },
            new Item() { contentId = 248, name = "Silk Robe", type = "Armor - Body", description = "A simple, lightweight silken robe." },
            new Item() { contentId = 249, name = "Mythril Vest", type = "Armor - Body", description = "A mythril vest that weighs next to nothing." },
            new Item() { contentId = 250, name = "Ninja Gear", type = "Armor - Body", description = "Ninja clothing from a faraway land." },
            new Item() { contentId = 251, name = "White Dress", type = "Armor - Body", description = "An attractive white dress that boosts the wearer's magic." },
            new Item() { contentId = 252, name = "Mythril Mail", type = "Armor - Body", description = "Dazzling plate mail forged entirely from mythril." },
            new Item() { contentId = 253, name = "Gaia Gear", type = "Armor - Body", description = "Clothing that absorbs earth damage." },
            new Item() { contentId = 254, name = "Mirage Vest", type = "Armor - Body", description = "A vest that creates illusionary images of the wearer." },
            new Item() { contentId = 255, name = "Golden Armor", type = "Armor - Body", description = "Brilliant gold armor emblazoned with a rearing unicorn." },
            new Item() { contentId = 256, name = "Power Sash", type = "Armor - Body", description = "A sash that strengthens the wearer." },
            new Item() { contentId = 257, name = "Luminous Robe", type = "Armor - Body", description = "A robe that shines with a mysterious inner light." },
            new Item() { contentId = 258, name = "Diamond Vest", type = "Armor - Body", description = "A breastplate with large diamonds set into its surface." },
            new Item() { contentId = 259, name = "Red Jacket", type = "Armor - Body", description = "Prized armor that negates fire damage." },
            new Item() { contentId = 260, name = "Force Armor", type = "Armor - Body", description = "Armor that halves damage from multiple elements." },
            new Item() { contentId = 261, name = "Diamond Armor", type = "Armor - Body", description = "A brilliant suit of armor fashioned from sheets of cut diamond." },
            new Item() { contentId = 262, name = "Black Garb", type = "Armor - Body", description = "Jet-black clothing from a distant land." },
            new Item() { contentId = 263, name = "Magus Robe", type = "Armor - Body", description = "A flowing robe woven in the age when magic still flourished." },
            new Item() { contentId = 264, name = "Crystal Mail", type = "Armor - Body", description = "A resplendent suit of crystal plate mail." },
            new Item() { contentId = 265, name = "Regal Gown", type = "Armor - Body", description = "An elegant dress designed to protect a princess." },
            new Item() { contentId = 266, name = "Genji Armor", type = "Armor - Body", description = "Armor forged in a foreign land by a master blacksmith." },
            new Item() { contentId = 267, name = "Reed Cloak", type = "Armor - Body", description = "A cloak made of reeds that is often worn by imps." },
            new Item() { contentId = 268, name = "Minerva Bustier", type = "Armor - Body", description = "A breastplate that blocks damage from multiple elements. Provides a 25% bonus to maximum MP." },
            new Item() { contentId = 269, name = "Tabby Suit", type = "Armor - Body", description = "A cat suit that negates poison damage." },
            new Item() { contentId = 270, name = "Chocobo Suit", type = "Armor - Body", description = "A feathery suit that negates poison...and brings out one's inner chocobo." },
            new Item() { contentId = 271, name = "Moogle Suit", type = "Armor - Body", description = "A moogle bodysuit that negates poison, kupo!" },
            new Item() { contentId = 272, name = "Nutkin Suit", type = "Armor - Body", description = "An oversized squirrel costume." },
            new Item() { contentId = 273, name = "Behemoth Suit", type = "Armor - Body", description = "A costume made from actual behemoth hide." },
            new Item() { contentId = 274, name = "Snow Scarf", type = "Armor - Body", description = "A scarf that absorbs ice and halves fire damage." },
            new Item() { contentId = 275, name = "Silver Spectacles", type = "Armor - Relic", description = "Silver-rimmed spectacles. Prevent darkness." },
            new Item() { contentId = 276, name = "Star Pendant", type = "Armor - Relic", description = "A star-shaped pendant with a jewel at its center. Prevents poison." },
            new Item() { contentId = 277, name = "Peace Ring", type = "Armor - Relic", description = "A ring that soothes its wearer's mind. Prevents berserk and confusion." },
            new Item() { contentId = 278, name = "Amulet", type = "Armor - Relic", description = "A protective charm worn around the neck. Prevents poison, darkness, and zombie." },
            new Item() { contentId = 279, name = "White Cape", type = "Armor - Relic", description = "A flowing white silk cape. Prevents imp and silence." },
            new Item() { contentId = 280, name = "Jeweled Ring", type = "Armor - Relic", description = "A handsome ring set with a large gemstone. Prevents petrification." },
            new Item() { contentId = 281, name = "Fairy Ring", type = "Armor - Relic", description = "A ring imbued with fairy magic. Prevents poison and darkness." },
            new Item() { contentId = 282, name = "Barrier Ring", type = "Armor - Relic", description = "A ring enchanted with a protective ward. Casts Shell when the wearer is critically wounded." },
            new Item() { contentId = 283, name = "Mythril Glove", type = "Armor - Relic", description = "A lightweight glove made of mythril. Casts Protect when the wearer is critically wounded." },
            new Item() { contentId = 284, name = "Protect Ring", type = "Armor - Relic", description = "A ring enchanted with with a protective ward. Casts Protect on the wearer." },
            new Item() { contentId = 285, name = "Hermes Sandals", type = "Armor - Relic", description = "Winged sandals enchanted for speed. Cast Haste on the wearer." },
            new Item() { contentId = 286, name = "Reflect Ring", type = "Armor - Relic", description = "A lustrous silver ring enchanted with a protective ward. Casts Reflect on the wearer." },
            new Item() { contentId = 287, name = "Angel Wings", type = "Armor - Relic", description = "Wings said to have been made from an angel's feathers. Cast Float on the wearer." },
            new Item() { contentId = 288, name = "Angel Ring", type = "Armor - Relic", description = "A ring adorned with a pair of silver angel wings. Casts Regen on the wearer." },
            new Item() { contentId = 289, name = "Knight's Code", type = "Armor - Relic", description = "A book detailing knighthood's moral code. Causes the bearer to cover critically wounded allies." },
            new Item() { contentId = 290, name = "Dragoon Boots", type = "Armor - Relic", description = "Steel boots made for dragoons. Change the Attack command to Jump." },
            new Item() { contentId = 291, name = "Zephyr Cloak", type = "Armor - Relic", description = "A cloak inhabited by the spirit of a wind sprite. Boosts evasion and magic evasion." },
            new Item() { contentId = 292, name = "Princess Ring", type = "Armor - Relic", description = "A beautiful ring designed to protect a royal daughter. Casts Protect and Shell when critically wounded." },
            new Item() { contentId = 293, name = "Cursed Ring", type = "Armor - Relic", description = "A ring said to have been forged by Death himself. Casts Doom on the wearer at the start of battle." },
            new Item() { contentId = 294, name = "Earring", type = "Armor - Relic", description = "A earring that boosts the strength of the wearer's magic. Effect increases when worn in a pair." },
            new Item() { contentId = 295, name = "Gigas Glove", type = "Armor - Relic", description = "A glove said to have belonged to a mighty gigas. Boosts the wearer's physical attack power." },
            new Item() { contentId = 296, name = "Blizzard Orb", type = "Armor - Relic", description = "A dark, swirling orb that absorbs ice and negates fire damage. Equip on a yeti and see what happens." },
            new Item() { contentId = 297, name = "Berserker Ring", type = "Armor - Relic", description = "A deep crimson ring that absorbs fire and negates lightning damage. Equip on a yeti and see what happens." },
            new Item() { contentId = 298, name = "Thief's Bracer", type = "Armor - Relic", description = "A bracer inhabited by the spirit of a thief. Increases the success rate of the Steal command." },
            new Item() { contentId = 299, name = "Guard Bracelet", type = "Armor - Relic", description = "A bracelet enchanted with a protective ward. Casts Protect and Shell on the wearer." },
            new Item() { contentId = 300, name = "Hero's Ring", type = "Armor - Relic", description = "A golden ring once worn by an ancient hero. Boosts both physical and magical attack power." },
            new Item() { contentId = 301, name = "Ribbon", type = "Armor - Relic", description = "A silk ribbon enchanted with powerful protective magic. Prevents all status ailments." },
            new Item() { contentId = 302, name = "Muscle Belt", type = "Armor - Relic", description = "A belt worn by martial artists. Boosts maximum HP by 50%." },
            new Item() { contentId = 303, name = "Crystal Orb", type = "Armor - Relic", description = "A powerful magic orb that holds a mysterious power. Boosts maximum MP by 50%." },
            new Item() { contentId = 304, name = "Gold Hairpin", type = "Armor - Relic", description = "A solid gold hairpin brimming with magical energy. Halves the MP cost of all magic." },
            new Item() { contentId = 305, name = "Celestriad", type = "Armor - Relic", description = "A necklace with three star-shaped bangles on its chain. Reduces the MP cost of all magic to 1." },
            new Item() { contentId = 306, name = "Brigand's Glove", type = "Armor - Relic", description = "A leather glove designed to aid in banditry. Changes the Steal command to Mug." },
            new Item() { contentId = 307, name = "Gauntlet", type = "Armor - Relic", description = "A steel hand and forearm guard used by knights. Allows one weapon to be held with both hands." },
            new Item() { contentId = 308, name = "Genji Glove", type = "Armor - Relic", description = "An armored glove from a foreign land. Allows the wearer to equip a weapon in each hand." },
            new Item() { contentId = 309, name = "Hyper Wrist", type = "Armor - Relic", description = "A studded bracelet that radiates a mysterious power. Boosts the wearer's strength." },
            new Item() { contentId = 310, name = "Master's Scroll", type = "Armor - Relic", description = "Proof of a warrior's weapon mastery. Allows the bearer to attack four times per turn." },
            new Item() { contentId = 311, name = "Prayer Beads", type = "Armor - Relic", description = "Beads used in meditation by warriors of a foreign land. Boosts evasion." },
            new Item() { contentId = 312, name = "Black Belt", type = "Armor - Relic", description = "A black cloth belt from a distant land. Allows the wearer to sometimes counter physical attacks." },
            new Item() { contentId = 313, name = "Heiji's Jitte", type = "Armor - Relic", description = "An exotic weapon from a foreign land. Changes the Slot command to Gil Toss." },
            new Item() { contentId = 314, name = "Fake Mustache", type = "Armor - Relic", description = "A fake mustache once worn by a circus ringmaster. Changes the Sketch command to Control." },
            new Item() { contentId = 315, name = "Soul of Thamasa", type = "Armor - Relic", description = "An ancient Thamasan orb that bears a wondrous power. Changes the Magic command to Dualcast." },
            new Item() { contentId = 316, name = "Dragon Horn", type = "Armor - Relic", description = "A horn inhabited by the spirit of a dragoon. Makes the effect of the Jump command continuous." },
            new Item() { contentId = 317, name = "Merit Award", type = "Armor - Relic", description = "A badge awarded in honor of great achievements. Allows the wearer to equip any weapon or armor." },
            new Item() { contentId = 318, name = "Memento Ring", type = "Armor - Relic", description = "A ring blessed by a departed mother's love. Prevents petrification, zombie, and instant death magic." },
            new Item() { contentId = 319, name = "Safety Bit", type = "Armor - Relic", description = "A tiny sphere that orbits its owner's head. Prevents petrification, zombie, and instant death magic." },
            new Item() { contentId = 320, name = "Lich Ring", type = "Armor - Relic", description = "A ring affected by a curse from beyond the grave. Makes the wearer undead." },
            new Item() { contentId = 321, name = "Molulu's Charm", type = "Armor - Relic", description = "A mysterious moogle charm for (MOG). Prevents all random enemy encounters." },
            new Item() { contentId = 322, name = "Ward Bangle", type = "Armor - Relic", description = "A bronze wristband enchanted with a protective ward. Lowers the rate of random enemy encounters." },
            new Item() { contentId = 323, name = "Miracle Shoes", type = "Armor - Relic", description = "Marvelous shoes with a number of useful enchantments. Cast Haste, Protect, Shell, and Regen on the wearer." },
            new Item() { contentId = 324, name = "Alarm Earring", type = "Armor - Relic", description = "An earring capable of detecting enemy ambushes. Prevents back attacks and attacks from the sides." },
            new Item() { contentId = 325, name = "Gale Hairpin", type = "Armor - Relic", description = "A hairpin imbued with the power of wind. Increases the frequency of preemptive strikes." },
            new Item() { contentId = 326, name = "Sniper Eye", type = "Armor - Relic", description = "A scope that allows the wearer to lock onto a target. Ensures that physical attacks never miss." },
            new Item() { contentId = 327, name = "Growth Egg", type = "Armor - Relic", description = "A strange egg with magical properties. Doubles the amount of EXP earned in battle." },
            new Item() { contentId = 328, name = "Tintinnabulum", type = "Armor - Relic", description = "A collar with a small bell that rings as the wearer walks. Restores some HP with each step taken." },
            new Item() { contentId = 329, name = "Sprint Shoes", type = "Armor - Relic", description = "Shoes enchanted to make the wearer move faster. Double walking speed." },
        };
    }
}
